// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type App struct {
	AppIndex       int64
	AppID          string
	AppSource      string
	AppOs          string
	AppRegistryID  string
	AppLastUpdated string
	AppStatus      string
	AppVersion     sql.NullString
	AppAvailable   sql.NullString
}

type Registry struct {
	RegistryID   string
	RegistryName string
}
